version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  pg-data:
